
trigger: none

pool:
  name: Ranjan_pool

steps:

# =========================================================
# 1. Install Terraform
# =========================================================
- task: TerraformInstaller@1
  displayName: 'Install Terraform'
  inputs:
    terraformVersion: 'latest'


# =========================================================
# 2. Terraform Init
# =========================================================
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent-Moudle'

    backendServiceArm: 'Ranjan_Service_Connection'
    backendAzureRmOverrideSubscriptionID: 'cf4adfd0-252d-4813-b002-f6f2095a23a8'
    backendAzureRmResourceGroupName: 'Ranjan_24'
    backendAzureRmStorageAccountName: 'ranjansingh24'
    backendAzureRmContainerName: 'ranjancontainer'
    backendAzureRmKey: 'ranjan.tfstate'


# =========================================================
# 3. Terraform Validate
# =========================================================
- task: TerraformTaskV4@4
  displayName: 'Terraform Validate'
  inputs:
    provider: 'azurerm'
    command: 'validate'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent-Moudle'


# =========================================================
# 4. Terraform Plan
# =========================================================
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent-Moudle'

    environmentServiceNameAzureRM: 'Ranjan_Service_Connection'
    environmentAzureRmOverrideSubscriptionID: 'cf4adfd0-252d-4813-b002-f6f2095a23a8'


# =========================================================
# 5. Terraform Apply
# =========================================================
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/Parent-Moudle'

    commandOptions: '-auto-approve'

    environmentServiceNameAzureRM: 'Ranjan_Service_Connection'
    environmentAzureRmOverrideSubscriptionID: 'cf4adfd0-252d-4813-b002-f6f2095a23a8'

